# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    python: "miniconda3-11"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: doc/source/conf.py

conda:
  environment: .readthedocs_environment.yml
