name: Test PyLag in Linux using Marketplace Miniconda
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-linux:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          python-version: 3.11
          auto-activate-base: false
      - name: Show conda env
        run: |
          conda info
          conda list
#      - name: Lint
#        shell: bash -l {0}
#        run: |
#            conda install flake8
#            python -m flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#            python -m flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run pytest
        run: |
            conda install pytest
            pytest
